target_jpos: [
    0, 0, 0,
    0, 0, 0,
    0, 0, 0,
    0, 0, 0]

#target_jpos: [
    #0., .0, .7,
    #0., .0, .7,
    #0., .0, .7,
    #0., .0, .7]


mid_jpos: [
    -0.4, 0.1, -0.1,
     0.4, 0.1, -0.1,
    -0.4, 0.1, -0.1,
     0.4, 0.1, -0.1]
