# Generated on Mon Aug  5 18:20:08 2019
__collection-name__: user-parameters
# Control parameter
tau_ff          : 0.0
kp              : 1.3
kd              : 1.6
zero            : 0
calibrate       : 0

# Leg config parameter
h               : 0.
hu              : 0.17
hl              : 0.17

# D-trajectory config parameter
lamda           : 0.5
time            : 20000
x_start         : 0
x_end           : 0.05
z_height        : 0.05
z_start         : -0.25
