# Generated on Mon Aug  5 18:20:08 2019
__collection-name__: user-parameters
# Control parameter
tau_ff     	: 0
kp		: 0.5
kd          	: 1
zero		: 0
calibrate	: 0

# Tarket toe position
pos_x		: 1
pos_y		: 1
pos_z		: 1 

# Leg config parameter
h		: 1
hu		: 1
hl		; 1


